### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by patrick-willems** [timyerg/venny4py#1]
Hey,

Thanks alot for the package, very useful. Found small mistake I think with the labels, e.g. when plotting 3 sets:

        #xe = [37, 63, 50] #x coordinats ORIGINAL
        #ye = [55, 55, 32] #y coordinats ORIGINAL

works better for me as :

        xe = [37, 50, 63] #x coordinats ADAPTED
        ye = [55, 32, 55] #y coordinats ADAPTED

**Comment by timyerg** [comment]
Hi!
Thank you for reporting the first bug!
Glad that this package is useful.

I checked the intersections and looks like I messed up not in the lines you posted but 114-116, it should be:

```
        #annotate
        xt = [12, 88, 28, 22, 78, 50, 50, 30, 70, 50] #x
        yt = [80, 80,  3, 60, 60, 17, 70, 35, 35, 50] #y
```

instead of

```
        #annotate
        xt = [12, 28, 88, 22, 78, 50, 50, 30, 70, 50] #x
        yt = [80,   3, 80, 60, 60, 17, 70, 35, 35, 50] #y
```

Please, check your diagram since you only fixed the general count of features but not intersections.

I updated the package, please update it:

`pip install venny4py==1.0.1`

Hopefully, it is fixed now. Let me know if there are some other issues or fix not working as supposed to.
