### ISSUE TITLE
Change the postion of legend

### ISSUE THREAD

**Issue by li081766** [timyerg/venny4py#4]
Dear,

Thanks for developing this fantastic tool.

I guess it's better to place the name of each set before the total number within the plot than to show the legend outside the plot. Use ":" to separate the set's name and total number so that, when interpreting the plot, we can directly get information about the names within the plot and do not need to get the information from the legend. This way is adopted in most circumstances, especially in most literature.   

Could you please consider revising the code following my advice?

Thanks,
Jia

**Comment by timyerg** [comment]
Dear Jia,
Thank you for the feedback.
Personally, I like the variant with legend much more because it handles better long names of the sets. So I would like to leave it as it is.

If you are into the coding, please feel free to fork the repo and modify it so it will give the desired output.

If you don't want to tweak the code, but you need a figure with set names plotted as you suggested, you can indicate ".svg" as extension and then modify legend in Inkscape software.

Best,
Timur

**Comment by li081766** [comment]
Dear Timur,

Thanks a lot.

I agree with you. It's always hard to deal with long names. Editing with Inkscape or Adobe AI is a good way to replace the legend. 

Best,
Jia
